### ISSUE TITLE
Order/Suggestion: Adding Marker Clusters on the Map Page

### ISSUE THREAD

**Issue by ddiaz2380** [nafiesl/laravel-leaflet-example#15]
I know it's an example and I appreciate you sharing your project which is great ... could you add markerclusterer please? Thanks a lot!

**Comment by nafiesl** [comment]
Hello @ddiaz2380, you mean adding this package, https://github.com/Leaflet/Leaflet.markercluster?

**Comment by ddiaz2380** [comment]
Hi @nafiesl .I tried to add that module and also a search bar by address, but I could not do it. We are implementing this module to take and show the cases of covid in my city. if you could help me it would be great!

**Comment by nafiesl** [comment]
Hello @ddiaz2380, I have added the marker clustering on PR #16. You can try it by pulling the git repo and checkout to the `marker_clusters` branch. See if it works on your side.

Related to your implementation for the covid mapping, I cannot help any further. You can use this project as a reference if you want.

Thanks for the github star for this project.

**Comment by nafiesl** [comment]
By the way, if you feel this project useful, you can buy me a coffee :smile: 
https://www.buymeacoffee.com/nafiesl

**Comment by ddiaz2380** [comment]
hi @nafiesl. Excellent !!! Yes, of course, a caffe invited him: D I was referring to the fact that we are implementing his example project in the covid shots of my city. Of course, it is referenced that to your repository, when we finish it I send you a link. On the other hand, I told him that we only needed to implement the clustermarket and a search on the map, for the search by address. I'll see how to implement that, very nice of you!
Thanks a lot!

**Comment by ddiaz2380** [comment]
hi @nafiesl  The cluster works perfect, but now the reference of the mark point popup has been lost

**Comment by nafiesl** [comment]
Hi @ddiaz2380 nice catch, Thank you.

I have just updated the `marker_clusters` branch, can you pull the latest commit again?

**Comment by ddiaz2380** [comment]
hi @nafieslNow if it is perfect! I don't have much experience in laravel, and less php. I come from python with django and the truth is that it costs me a lot, I am going to invite you a caffe in the first days of April, I leave it scheduled. Thank you so much for everything!

P / D: Above all, my people are grateful that with this app we will be able to relieve COVID cases, Thank you!
It is very difficult to add a search bar on the map by Outlet Name and that also in that same bar you can put an address and position the point in that address address?

**Comment by nafiesl** [comment]
> I am going to invite you a caffe in the first days of April, I leave it scheduled.

Hehe.. nice, thanks @ddiaz2380.

> It is very difficult to add a search bar on the map by Outlet Name and that also in that same bar you can put an address and position the point in that address address?

@ddiaz2380, you mean adding some search bar like this on the map page (`/our_outlets`)?

![screen_2021-03-31_002](https://user-images.githubusercontent.com/8721551/113094152-c74aa280-9223-11eb-96cd-37d164c5eaa9.jpg)

**Comment by ddiaz2380** [comment]
But that is if you have a user, I mean to put it on the map publicly. By putting a street address and height I took the point to that address. As well as if I put the name of the Outlets I placed myself in it. Example: https://github.com/bavix/laravel-admin-leaflet

![Captura de Pantalla 2021-03-31 a la(s) 02 47 42](https://user-images.githubusercontent.com/57850481/113096529-b79f6f80-91cb-11eb-9f48-ba3f04c7fe19.png)

**Comment by nafiesl** [comment]
@ddiaz2380 sorry I didn't get your point 😕 I thought you wew suggesting a search bar for outlet name or address.

But I think it's beyond the scope of your first sugestion for adding a marker clustering feature.

I am suggesting you create a new issue for another feature proposal. What do you think, @ddiaz2380?

**Comment by ddiaz2380** [comment]
I understand and thank you for all your time and good disposition, I owe you the coffee in the first days I charge and I invite you: D.
I meant to add an address search like this: https://codepen.io/exomark/pen/dafBD

**Comment by nafiesl** [comment]
> I understand and thank you for all your time and good disposition, I owe you the coffee in the first days I charge and I invite you: D.

You're welcome, it's nice to know if that this little project helpful for someone. :grinning: 

> I meant to add an address search like this: https://codepen.io/exomark/pen/dafBD

Ah, ok I will do some research for that search part.

For now, let's close this issue then raise a new issue for the search feature.
