### ISSUE TITLE
Laravel Upgrade to 6.x

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/laravel-leaflet-example#2]
This project currently using Laravel 5.8.*. I am offering someone to help to upgrade it to Laravel 6.x.

A pull request will be helpful for me.

**Comment by AnBusse** [comment]
Hi, I'd like to help with this issue!

**Comment by nafiesl** [comment]
Sure, @AnBusse thanks.

**Comment by AnBusse** [comment]
@nafiesl I got the code ready locally, but I can't push to the remote (403 error). Could you please check if I have the correct permissions to push to the repo?

**Comment by vanduc1102** [comment]
@AnBusse , clone the repos to your github account, when you push change to the repos in your account, you will see a place to create a PR,
welcome to github

**Comment by AnBusse** [comment]
@vanduc1102 that seems like a weird way of doing things, but thanks for the info, appreciate it

**Comment by SAMSULROHMAN** [comment]
Hi, I'd like to help with this issue!

l try to add update to laravel 6 and add acl

**Comment by nafiesl** [comment]
@SAMSULROHMAN, sorry for this issue, @AnBusse already create PR #3.

**Comment by aznadesign** [comment]
@nafiesl check this pull request for this issue.
[https://github.com/nafiesl/laravel-leaflet-example/pull/5](https://github.com/nafiesl/laravel-leaflet-example/pull/5)

**Comment by nafiesl** [comment]
Closed by this PR #5, thanks @aznadesign for helping me.
